import React, { useState } from 'react';
import { Bot, RefreshCw, AlertCircle } from 'lucide-react';
import { StockDataPoint, Ticker } from '../types';
import { analyzeStockSentiment } from '../services/geminiService';
import ReactMarkdown from 'react-markdown';

interface AnalysisPanelProps {
  ticker: Ticker;
  data: StockDataPoint[];
}

export const AnalysisPanel: React.FC<AnalysisPanelProps> = ({ ticker, data }) => {
  const [analysis, setAnalysis] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const handleAnalyze = async () => {
    setLoading(true);
    // Grab last 5 days
    const recentData = data.slice(-5);
    const result = await analyzeStockSentiment(ticker, recentData);
    setAnalysis(result);
    setLoading(false);
  };

  return (
    <div className="bg-gray-900/50 rounded-xl border border-gray-800 p-6 h-full flex flex-col">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <Bot className="w-5 h-5 text-indigo-400" />
          <h3 className="text-gray-100 font-semibold">AI Quantitative Analyst</h3>
        </div>
        <button
          onClick={handleAnalyze}
          disabled={loading}
          className={`flex items-center gap-2 px-3 py-1.5 rounded-md text-sm font-medium transition-all ${
            loading 
              ? 'bg-gray-800 text-gray-500 cursor-not-allowed' 
              : 'bg-indigo-600 hover:bg-indigo-500 text-white shadow-lg shadow-indigo-500/20'
          }`}
        >
          {loading ? (
            <RefreshCw className="w-4 h-4 animate-spin" />
          ) : (
            <RefreshCw className="w-4 h-4" />
          )}
          {loading ? 'Analyzing...' : 'Generate Report'}
        </button>
      </div>

      <div className="flex-1 overflow-y-auto min-h-[200px] bg-gray-950/50 rounded-lg border border-gray-800 p-4">
        {!analysis ? (
          <div className="h-full flex flex-col items-center justify-center text-gray-500 gap-3">
            <div className="p-3 bg-gray-900 rounded-full">
               <Bot className="w-8 h-8 opacity-50" />
            </div>
            <p className="text-sm text-center max-w-[250px]">
              Click "Generate Report" to have Gemini analyze the correlation between recent sentiment headlines and price action.
            </p>
          </div>
        ) : (
          <div className="prose prose-invert prose-sm max-w-none">
            <ReactMarkdown>{analysis}</ReactMarkdown>
          </div>
        )}
      </div>
      
      <div className="mt-4 flex items-start gap-2 text-xs text-gray-500">
        <AlertCircle className="w-3 h-3 mt-0.5 flex-shrink-0" />
        <p>
          Analysis generated by Gemini 2.5 Flash using simulated sentiment data. 
          The "Advanced Model" includes FinBERT sentiment scores in its feature set.
        </p>
      </div>
    </div>
  );
};
